CXXFLAGS  = -O3 -m64
CXXFLAGS += -Wall
CXXFLAGS += -Wextra
#CXXFLAGS += -pedantic
CXXFLAGS += -Weffc++
CXXFLAGS += -std=c++17
CXXFLAGS += -fext-numeric-literals

LDFLAGS = -lquadmath

all:
	$(CXX) -c *.cpp $(CXXFLAGS)
